alpha = 1.0
disabledAlpha = 0.4000000059604645
windowPadding = [10.0, 10.0]
windowRounding = 4.0
windowBorderSize = 0.0
windowMinSize = [100.0, 100.0]
windowTitleAlign = [0.5, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 1.0
popupBorderSize = 1.0
framePadding = [5.0, 3.0]
frameRounding = 3.0
frameBorderSize = 0.0
itemSpacing = [6.0, 6.0]
itemInnerSpacing = [3.0, 2.0]
cellPadding = [3.0, 3.0]
indentSpacing = 6.0
columnsMinSpacing = 6.0
scrollbarSize = 13.0
scrollbarRounding = 16.0
grabMinSize = 20.0
grabRounding = 4.0
tabRounding = 4.0
tabBorderSize = 1.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(219, 237, 226, 1.0)"
TextDisabled = "rgba(133, 140, 136, 1.0)"
WindowBg = "rgba(33, 35, 43, 1.0)"
ChildBg = "rgba(38, 40, 48, 1.0)"
PopupBg = "rgba(51, 56, 68, 1.0)"
Border = "rgba(35, 29, 34, 1.0)"
BorderShadow = "rgba(0, 0, 0, 1.0)"
FrameBg = "rgba(43, 47, 59, 1.0)"
FrameBgHovered = "rgba(116, 50, 76, 1.0)"
FrameBgActive = "rgba(116, 50, 76, 1.0)"
TitleBg = "rgba(59, 51, 69, 1.0)"
TitleBgActive = "rgba(128, 19, 65, 1.0)"
TitleBgCollapsed = "rgba(51, 56, 68, 1.0)"
MenuBarBg = "rgba(51, 56, 68, 1.0)"
ScrollbarBg = "rgba(61, 61, 56, 1.0)"
ScrollbarGrab = "rgba(99, 99, 95, 1.0)"
ScrollbarGrabHovered = "rgba(177, 177, 175, 1.0)"
ScrollbarGrabActive = "rgba(177, 177, 175, 1.0)"
CheckMark = "rgba(168, 35, 45, 1.0)"
SliderGrab = "rgba(166, 38, 88, 1.0)"
SliderGrabActive = "rgba(181, 56, 68, 1.0)"
Button = "rgba(166, 38, 88, 1.0)"
ButtonHovered = "rgba(128, 19, 65, 1.0)"
ButtonActive = "rgba(116, 50, 76, 1.0)"
Header = "rgba(116, 50, 76, 1.0)"
HeaderHovered = "rgba(166, 38, 88, 1.0)"
HeaderActive = "rgba(128, 19, 65, 1.0)"
Separator = "rgba(109, 109, 127, 1.0)"
SeparatorHovered = "rgba(25, 102, 191, 1.0)"
SeparatorActive = "rgba(25, 102, 191, 1.0)"
ResizeGrip = "rgba(166, 38, 88, 1.0)"
ResizeGripHovered = "rgba(116, 50, 76, 1.0)"
ResizeGripActive = "rgba(116, 50, 76, 1.0)"
Tab = "rgba(45, 89, 147, 1.0)"
TabHovered = "rgba(66, 150, 249, 1.0)"
TabActive = "rgba(50, 104, 173, 1.0)"
TabUnfocused = "rgba(17, 26, 37, 1.0)"
TabUnfocusedActive = "rgba(34, 66, 108, 1.0)"
PlotLines = "rgba(219, 237, 226, 1.0)"
PlotLinesHovered = "rgba(116, 50, 76, 1.0)"
PlotHistogram = "rgba(79, 198, 50, 1.0)"
PlotHistogramHovered = "rgba(116, 50, 76, 1.0)"
TableHeaderBg = "rgba(48, 48, 51, 1.0)"
TableBorderStrong = "rgba(79, 79, 89, 1.0)"
TableBorderLight = "rgba(58, 58, 63, 1.0)"
TableRowBg = "rgba(0, 0, 0, 1.0)"
TableRowBgAlt = "rgba(255, 255, 255, 1.0)"
TextSelectedBg = "rgba(98, 160, 234, 1.0)"
DragDropTarget = "rgba(255, 255, 0, 1.0)"
NavHighlight = "rgba(66, 150, 249, 1.0)"
NavWindowingHighlight = "rgba(255, 255, 255, 1.0)"
NavWindowingDimBg = "rgba(204, 204, 204, 1.0)"
ModalWindowDimBg = "rgba(204, 204, 204, 0.300000011920929)"
